language: node_js

cache: yarn

script: ""

deploy:
  - provider: npm
    email:
      secure: KwAcuSudRbUAiU/WJm63M2x2YgU4sWdPpPVsmhDa6877OjWT/MxWfoNtRRgSOfOTmlH2Mzr6bl97nZVL9KcYGTq5oc32yG6PRe8vHsvo9A+sriOr9IlCs8Sf/Yh3GAkXeBNyw7UGV+z/bCj+80Mfm5/sgm3n2igfi0bcZ0LPy6GWqhQS27rShK6US35XI84Ug0f5OoZ7EVcsgmuPl53n1GSu/ywJtp0QsDX0R02hzWNBLFylivYvN64Hqs5TKQ3xCUZWQcxfXmjLR2RF2hUQ4FmEYvbww1QPk0K0ezDjpPjeR5B8hnmNf5wQJD6Dm1bQMU/03rSF7bcFGiCCmw3l7nww/qVtOiwqxcgGI+D5WAI61bSyWNWxstTA8mxo7p2tZxVMBRTfoM2v+nBAjHSVfe8C1AHL3HIYA+IhLzjxfqqo5rm9ioKjjKrxrIuEujmbAnTftUvIgIbyMy0BhajBaIX0BstSpjzEvYzRAJBp317v5J0WJyVawt0v2K6UJyZUM+4kw5+GCO5dj2Vu9N7/3JXZxh7c1JQlq91hd2V+CPhJWxyQnnqGKusLsuTgXBDMK8vNG63PEbHzx6ZV1MtBwvfTgHFqU26BLfuBQb8fD81eR+RN+Z/r57ZgG4l6Dl3UN0woH5S4HeA7bKMwoutzO11Yz/xL1cHVvcdvMtZ2TAo=
    api_key:
      secure: H8Jf69Zs3kzNXJ9G+8YPnB8E0wciRD/lfBBRe/3co5/uJYiouEESFV+srAvIW3dsye2WnhH7LE0LkmUb/1+De5kcO6z4cXSsuviI6Z+6jC6E6iOBGts7pWfEaMkRsd+HlkzKGgBttw7VudgHj3uI5FjTHbUyWMgpH3RbC/5BDwrhmjCqyHc+s9pJGlTiteJ/UHmuRvoesJtRrJIuWVZ0ytP0Gidv+SVSNEpZv+BNjnsBq1BqF6wCGWJIYKg55H7pc4gPbLZ1QQEPb9vZfme5ObgPYj6o6OtIEWM4sGcQfpEV2dSH34gfZgCCwcztt31UZSRzVMJ71pVCYqNuNoCzac8NUITIEw7ATeagq3WhLkDCLRBW/45+TFJ3enc4/NFYXPgxtJPnTXrBBAcsBOfBpYaLUBql7a5e75LamTq+P8asCktcUT6/jN9lpji2Dr7LosG3bqILZM9/54XkEXBvaCLRDw3cblhs7lV2DMyPrfGQB3eexo9dgGnAAzrbVIYJILfHadS7jLqnq8aFrrdguMXTpOqTjnADDrY/SNv6QGS2fpBf63zOwuePMrTsFw7JV5wBX5Y5j+C4JCAEcJoz9lczYRA0j0Tskd3ScBYrtI4FgjWIZFrWufjxfklrKc+xa/5dNXhkJCRjoXfiWlQzhb4J3nqitXAlGDVPJx31MmA=
    on:
      tags: true
